//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoSaloonDataEntities : DbContext
    {
        public AutoSaloonDataEntities()
            : base("name=AutoSaloonDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Franchise> Franchises { get; set; }
        public virtual DbSet<FranchisePackage> FranchisePackages { get; set; }
        public virtual DbSet<FranchiseProduct> FranchiseProducts { get; set; }
        public virtual DbSet<FranchiseUser> FranchiseUsers { get; set; }
        public virtual DbSet<LoginDetail> LoginDetails { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<PackageProduct> PackageProducts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    }
}
