//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDesc { get; set; }
        public decimal ProductPrice { get; set; }
        public Nullable<int> ProductMinDiscountPercentage { get; set; }
        public string ProductMaxDiscountPercentage { get; set; }
        public byte[] ProductImage { get; set; }
        public Nullable<bool> ProductIsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatorId { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public int LastModifierID { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeleterID { get; set; }
    }
}
